version: "3"
services:
  server:
    build: .
    ports:
      - 8080:80
    volumes:
      - ./server_src:/var/www/html
      - ./conf/000-default.conf:/etc/apache2/sites-available/000-default.conf
    links:
      - db
  db:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=secret
